- name: Copy the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install {{COMPONENT}}
  ansible.builtin.package:
      name: mongodb-org
      state: present

- name: Update {{COMPONENT}} listening address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting {{COMPONENT}}
  ansible.builtin.service: 
    name: mongod
    state: started
    enabled: yes

- name: Download and extracting {{COMPONENT}} from github
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-github

## To install it, use: ansible-galaxy collection install community.mongodb
- name: Loading Catalogue and Users Schemas
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue 
    - users

# Ensure to run this at the end of all the tasks only.
- name: Disabling auto shutdown and setting hostname for {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname

- name: Adding the task indicating that mongodb config is completed
  debug: 
    msg: Mongodb config is completed
