- name: Demo on variables
  hosts: all
  vars:
    URL: play.google.com # These are global variables or play level variables
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: The value of URL is {{ URL }}

   tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: The value of URL is {{ URL }}
      vars:
        URL: task.google.com # These are local variables
