- name: Playbook to setup the roboshop project 
  hosts: frontend 
  become: yes   
  roles:  
    - frontend

- name: Download and extract
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes