- name: Playbook to setup the roboshop project 
  hosts: "{{ COMPONENT }}"
  # hosts: localhost      #Use it for pull only
  become: yes             # Runs the whole playbook as a root user 
  roles:  
    - "{{ COMPONENT }}"
 