- name: Install nginx
  ansible.builtin.package:
    name: nginx 
    state: present 

# - name: Download and extracting {{COMPONENT}}
#   ansible.builtin.include_role:
#     name: common 
#     tasks_from: download 

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path:  home/centos/{{COMPONENT}}
    state: directory
    mode: '0755'


# Download from Nexus
- name: Download and extracting {{COMPONENT}} from Nexus
  ansible.builtin.unarchive: 
    src: "{{REPO_URL}}"
    dest: /home/centos/{{COMPONENT}}
    remote_src: yes   ## This will be yes, if the source file is not in the ANSIBLE SERVER


- name: Cleanup of Old HTML Content 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent    # Absent deletes the files.

# Use it for Github only
# - name: copy of frontend content to nginx path 
#   ansible.builtin.copy:
#      src: /tmp/frontend-main/static/
#      dest: /usr/share/nginx/html
#      remote_src: yes


- name: copy of frontend content to nginx path 
  ansible.builtin.copy:
     src: /home/centos/{{COMPONENT}}/{{COMPONENT}}-main/static/
     dest: /usr/share/nginx/html
     remote_src: yes

# If src and dest ends with /, it's very important to know what you're aming directory, not just the content.
- name: copy the proxy file 
  ansible.builtin.template:
     src: roboshop.conf
     dest: /etc/nginx/default.d/roboshop.conf
  notify: Restart-Nginx   # When ever there is a change in this file, restart of nginx will happen

# This happens only when the service is installed. As rest of the times it will be up.
- name: Start Nginx  
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes 

- name: Set-hostname 
  ansible.builtin.include_role:
    name: common 
    tasks_from: set-hostname 