- name: Copy the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install {{COMPONENT}}
  ansible.builtin.package:
      name: 
        - mysql-community-server
        - MySQL-python
      state: present

- name: Starting {{COMPONENT}}
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: Check the DB Password 
  community.mysql.mysql_info:
    login_user: root 
    login_password: RoboShop@1
  ignore_errors: yes
  register: mysql_stat

- name: Reset Password
  debug:
    msg: Resetting the password and rthe info is {{mysql_stat}}
  when: mysql_stat.failed
  