# # Download from Github
# - name: Download and extracting {{COMPONENT}}
#   ansible.builtin.unarchive: 
#     src: "{{REPO_URL}}"
#     dest: /tmp
#     remote_src: yes   ## This will be yes, if the source file is not in the ANSIBLE SERVER

# Download from Nexus
- name: Download and extracting {{COMPONENT}} from Nexus
  ansible.builtin.unarchive: 
    src: "{{REPO_URL}}"
    dest: /tmp/{{COMPONENT}}
    remote_src: yes   ## This will be yes, if the source file is not in the ANSIBLE SERVER
