- name: Download and extracting {{COMPONENT}}
  ansible.builtin.unarchive: 
    src: "{{REPO_URL}}"
    dest: /tmp
    remote_src: yes   ## This will be yes, if the source file is not in the ANSIBLE SERVER