- name: Configure Yum repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
      name: 
        - nodejs
        - gcc-c++
      state: present

- name: Creating Appuser account {{APPUSER}}
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user

- name: Download and extracting {{COMPONENT}} from github
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-github

- name: Cleanup of {{COMPONENT}}
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent

- name: Copy the {{COMPONENT}} content to {{APPUSER}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    remote_src: yes 
  become_user: "{{APPUSER}}"